# Generated by Django 4.0.3 on 2022-04-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='header_image',
        ),
    ]
