# Generated by Django 4.0.3 on 2022-04-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_remove_blog_header_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_main_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.URLField(default='https://images.pexels.com/photos/6071881/pexels-photo-6071881.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', max_length=250),
        ),
    ]
